#! /bin/sh

###########################
##     Configuration     ##
###########################

killall sxhkd &
sxhkd &
~/.fehbg &
picom & --config ~/.config/picom/picom.conf -b &
sh ~/.config/polybar/launch.sh &
#/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start mouse
xsetroot -cursor_name left_ptr &

#Single monitor
#bspc monitor -d 1 2 3 4 5 6 7 8 9 10

#Dual monitor
#find out names with arandr or xrandr
#bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
#bspc monitor LVDS1 -d 1 2 3 4
#bspc monitor DP3 -d  5 6 7 8 9
#bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI2 -d 6 7 8 9 10

# Border
bspc config border_width         2
bspc config normal_border_color "#555555"
bspc config active_border_color "#ff3a0f"
bspc config focused_border_color "#ff3a0f"
bspc config presel_feedback_color "#14191f"

# Gaps and padding
bspc config window_gap          30
bspc config top_padding         61
bspc config right_padding       10
bspc config bottom_padding      10
bspc config left_padding        10

bspc config split_ratio          0.5

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config remove_disabled_monitors	true
bspc config remove_unplugged_monitors	true

##################
## Window rules ##
##################

# Rules
bspc rule -a Gparted state=floating follow=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Spotify state=floating

# Plasma rules
bspc rule -a plasmashell state=floating
bspc rule -a Plasma state=floating
bspc rule -a plasma-desktop state=floating
bspc rule -a krunner state=floating
bspc rule -a Kmix state=floating
bspc rule -a Klipper state=floating
bspc rule -a Plasmoidviewer state=floating
bspc rule -a Nightly state=tiled

# Wallpaper
feh --bg-scale ~/Pictures/Wallpapers/wall.jpg for HDMI1 ~/Pictures/Wallpapers/wall.jpg for eDP1
gsettings set org.gnome.desktop.background picture-uri file:///home/vic/Pictures/Wallpapers/wall.jpg 
